// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOm3w4R7AMWla5-H1AJYhqpsL24E2VOc',
    appId: '1:363259286544:web:0cbc3f502d75c5dca02695',
    messagingSenderId: '363259286544',
    projectId: 'recipe-recommendation-bc8a1',
    authDomain: 'recipe-recommendation-bc8a1.firebaseapp.com',
    storageBucket: 'recipe-recommendation-bc8a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdp2uR7Kak3hZZYaTyN8scY3Ozl0hoq2o',
    appId: '1:363259286544:android:deb862645437f42ba02695',
    messagingSenderId: '363259286544',
    projectId: 'recipe-recommendation-bc8a1',
    storageBucket: 'recipe-recommendation-bc8a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNmbXb7DXSxOH4Kjc7wQFrdXWEzCtkWmA',
    appId: '1:363259286544:ios:807c9c70f6bd92c1a02695',
    messagingSenderId: '363259286544',
    projectId: 'recipe-recommendation-bc8a1',
    storageBucket: 'recipe-recommendation-bc8a1.appspot.com',
    androidClientId: '363259286544-0qrahrl2mi2h8h8e3h5ob8kej274e67g.apps.googleusercontent.com',
    iosClientId: '363259286544-h2opvbvd8bp2e4qspps5ndjuf20knftu.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeRecommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNmbXb7DXSxOH4Kjc7wQFrdXWEzCtkWmA',
    appId: '1:363259286544:ios:89f6af7aac0cc95da02695',
    messagingSenderId: '363259286544',
    projectId: 'recipe-recommendation-bc8a1',
    storageBucket: 'recipe-recommendation-bc8a1.appspot.com',
    androidClientId: '363259286544-0qrahrl2mi2h8h8e3h5ob8kej274e67g.apps.googleusercontent.com',
    iosClientId: '363259286544-acchl02n13sdn728dr7g1upcrebbglia.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeRecommendation.RunnerTests',
  );
}
